PACKAGE_NAME: "dataprocessor"
CONFIG_PATH: "/home/giangnmt/Vnpt_AI/AirflowProject/example_config/code_config/data_processing_code_config.yaml"
VENV_HUB_PATH: "/home/giangnmt/VENV/"
RAW_REPO_URL: "git@github_dataprocessing_host:giangnmt98/DataProcessing.git"
PACKAGE_VERSION: "v1.0-gpu"
PYTHON_VERSION: "3.10"
